[project]
name = "youtube-transcriber"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pywhispercpp>=1.4.0",
    "yt-dlp>=2025.11.12",
]
